apiVersion: v1
entries:
  vtbhelm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-05-26T10:35:36.699148341+07:00"
    description: A Helm chart for Kubernetes
    digest: 785fe11eca56a13cb1d24a50165b9ebc6d46bf70f750cc810688695593cd9a6b
    name: vtbhelm
    type: application
    urls:
    - https://github.com/ThienNguyen2207/helmpublicrepo.git/vtbhelm-0.1.0.tgz
    version: 0.1.0
generated: "2023-05-26T10:35:36.698220922+07:00"
